services:

  db:
    image: mysql
    container_name: tennix_bdd
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tennix_db
      MYSQL_USER: benjamin
      MYSQL_PASSWORD: password
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_tennix
    ports:
      - "8741:80"
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
